version: "3"
services:
  db:
    image: postgres:16.1
    restart: always
    ports:
      - 5432:5432
    networks:
      - my-pg-network
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - /home/grinv/data/:/data/pg

networks:
  my-pg-network:
    driver: bridge
