version: "3.8"
services:
  nginx:
    image: nginx:1.25
    deploy:
      mode: global
    ports:
      - 8080:80
    configs:
      - source: nginxConfig
        target: /etc/nginx/conf.d/default.conf
      - source: nginxIndex
        target: /usr/share/nginx/html/index.html
    networks:
      - myNetwork
  db:
    image: postgres:16.1
    deploy:
      placement:
        constraints:
          - "node.labels.db==true"
    ports:
      - 5432:5432
    networks:
      - myNetwork
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

networks:
  myNetwork:
    driver: overlay

configs:
  nginxConfig:
    file: ./default.conf
  nginxIndex:
    file: ./index.html
