version: "3"
services:
  prometheus:
    image: prom/prometheus:v2.50.1
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    networks:
      - mynetwork
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  prometheus_data: {}

networks:
  mynetwork:
    external: true
