---
- name: Создать юзера
  loop: "{{ users }}"
  ansible.builtin.user:
    name: "{{ item.login }}"
    password: "{{ item.password | string | password_hash }}"
    group: docker

- name: Применить сгенерированный ssh ключ для юзера
  loop: "{{ users }}"
  become: true
  ansible.posix.authorized_key:
    user: "{{ item.login }}"
    state: present
    key: "{{ lookup('file', '{{ local_ssh_path }}/{{ local_ssh_file_prefix }}{{ item.login }}.pub') }}"
